[tool.poetry]
name = "mytardis-ime"
version = "0.1.0"
description = "An ingestion metadata editor for MyTardis"
authors = ["Noel <noel.zeng@auckland.ac.nz>"]

[tool.poetry.dependencies]
python = "^3.8"
PyQt5 = "^5.15.6"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pylint = "^2.13.9"
rope = "^1.1.1"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
